#!/usr/bin/env python3
"""Static fallback for /product/etc/build-manifest.xml.

LineageOS generates that file with `repo manifest -r`, which needs every project's git objects.
On the galilei build host the git objects were purged to free disk space, so this script
assembles an (unpinned) snapshot from the checked-out manifest files instead:
  .repo/manifests/default.xml + its <include>d snippets + .repo/local_manifests/*.xml
Usage (from the tree root): python3 device/beelink/galilei/gen-build-manifest.py [> out]
"""
import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.getcwd()
MANIFESTS = os.path.join(ROOT, ".repo", "manifests")


def load(path, seen):
    """Return the list of child elements of <manifest> in `path`, expanding <include>."""
    if path in seen or not os.path.isfile(path):
        return []
    seen.add(path)
    out = []
    for el in ET.parse(path).getroot():
        if el.tag == "include":
            out += load(os.path.join(MANIFESTS, el.get("name", "")), seen)
        else:
            out.append(el)
    return out


def main():
    seen = set()
    elements = load(os.path.join(MANIFESTS, "default.xml"), seen)
    for lm in sorted(glob.glob(os.path.join(ROOT, ".repo", "local_manifests", "*.xml"))):
        elements += load(lm, seen)
    root = ET.Element("manifest")
    root.append(ET.Comment(" unpinned snapshot generated by device/beelink/galilei/gen-build-manifest.py "
                           "(git objects unavailable on the build host; revisions are branch names) "))
    for el in elements:
        if el.tag == "project" and re.search(r"proprietary_", el.get("name", "")):
            continue
        root.append(el)
    ET.indent(root, space="  ")
    sys.stdout.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    sys.stdout.write(ET.tostring(root, encoding="unicode"))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
