#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

# Not set in time to check, so set before everything else
PRODUCT_IS_ATV := true

# Inherit some common AOSP stuff
$(call inherit-product, device/google/atv/products/atv_base.mk)

# Inherit some common Lineage stuff
$(call inherit-product, vendor/lineage/config/common_full_tv.mk)

# Inherit device configuration
$(call inherit-product, $(LOCAL_PATH)/device.mk)

## Device identifier. This must come after all inclusions
PRODUCT_BRAND := Beelink
PRODUCT_DEVICE := galilei
PRODUCT_MANUFACTURER := AZW
PRODUCT_MODEL := GT-King
PRODUCT_NAME := lineage_galilei

PRODUCT_GMS_CLIENTID_BASE := android-droid-tv

# Same blob source as the rest of the G12 family (ADT-3, Android 13)
PRODUCT_BUILD_PROP_OVERRIDES += \
    BuildDesc="adt3-user 13 TTT1.230205.001 9565391 release-keys" \
    BuildFingerprint=ADT-3/adt3/adt3:13/TTT1.230205.001/9565391:user/release-keys \
    SystemName=galilei

# Google apps for Android TV baked into the image (generated by
# lineage/scripts/make-gapps-vendor.py from the MindTheGapps *-arm-ATV zip during
# setup-tree.sh; absent = vanilla build). The box has no usable USB gadget, so a
# recovery sideload is not an option for users.
-include vendor/mindthegapps-atv/gapps.mk
