#!/usr/bin/env python3
"""Generate privapp-permissions allowlist XMLs for prebuilt privileged apps (MindTheGapps etc.).

    python3 gen-privapp-allowlist.py <TOP> <proprietary-dir> <out-dir> [--aapt2 PATH]

For every <part>/priv-app/<Name>/<Name>.apk under <proprietary-dir> (part = product, system_ext,
system) it lists the requested permissions (aapt2 dump permissions), keeps the ones the platform
declares as signature|privileged (frameworks/base/core/res/AndroidManifest.xml) and writes
<out-dir>/<part>/etc/permissions/privapp-permissions-galilei-<part>.xml with all of them.
Why: with ro.control_privapp_permissions=enforce (LineageOS default) system_server throws
"Signature|privileged permissions not in privileged permission allowlist" and reboots in a loop
when a priv-app requests one that no XML lists; the MindTheGapps XMLs miss several (READ_LOGS,
DUMP, MANAGE_LOW_POWER_STANDBY, TURN_SCREEN_ON, BLUETOOTH_PRIVILEGED, MANAGE_USERS, ...).
Listing every requested privileged permission is what AOSP's privapp_permissions.py does too;
entries for permissions an app never requests are harmless.
"""
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

ANDROID = "{http://schemas.android.com/apk/res/android}"


def platform_privileged(top):
    man = os.path.join(top, "frameworks/base/core/res/AndroidManifest.xml")
    root = ET.parse(man).getroot()
    out = set()
    for p in root.iter("permission"):
        level = p.get(ANDROID + "protectionLevel", "")
        parts = set(level.split("|"))
        if ("signature" in parts or "signatureOrSystem" in parts) and "privileged" in parts:
            out.add(p.get(ANDROID + "name"))
    return out


def requested(aapt2, apk):
    r = subprocess.run([aapt2, "dump", "permissions", apk], capture_output=True, text=True)
    names = set()
    for line in r.stdout.splitlines():
        m = re.match(r"\s*uses-permission(?:-sdk-23)?: name='([^']+)'", line)
        if m:
            names.add(m.group(1))
    pkg = re.search(r"^package: (\S+)", r.stdout, re.M)
    return (pkg.group(1) if pkg else None), names


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    top, prop, outdir = args[0], args[1], args[2]
    aapt2 = None
    if "--aapt2" in sys.argv:
        aapt2 = sys.argv[sys.argv.index("--aapt2") + 1]
    for cand in (aapt2, os.path.join(top, "out/host/linux-x86/bin/aapt2"),
                 os.path.join(top, "prebuilts/sdk/tools/linux/bin/aapt2")):
        if cand and os.path.exists(cand):
            aapt2 = cand
            break
    else:
        raise SystemExit("no aapt2 found")
    priv = platform_privileged(top)
    print("platform signature|privileged permissions: %d" % len(priv))
    written = []
    for part in ("product", "system_ext", "system"):
        d = os.path.join(prop, part, "priv-app")
        if not os.path.isdir(d):
            continue
        entries = []
        for name in sorted(os.listdir(d)):
            apk = os.path.join(d, name, name + ".apk")
            if not os.path.exists(apk):
                continue
            pkg, names = requested(aapt2, apk)
            keep = sorted(names & priv)
            if pkg and keep:
                entries.append((pkg, name, keep))
        if not entries:
            continue
        lines = ['<?xml version="1.0" encoding="utf-8"?>',
                 '<!-- Generated by lineage/scripts/gen-privapp-allowlist.py: every signature|privileged',
                 '     permission requested by the prebuilt privileged apps on /%s. -->' % part,
                 '<permissions>']
        for pkg, name, keep in entries:
            lines.append('    <privapp-permissions package="%s">  <!-- %s -->' % (pkg, name))
            lines += ['        <permission name="%s"/>' % n for n in keep]
            lines.append('    </privapp-permissions>')
        lines.append('</permissions>')
        rel = os.path.join(part, "etc", "permissions", "privapp-permissions-galilei-%s.xml" % part)
        path = os.path.join(outdir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, "w").write(chr(10).join(lines) + chr(10))
        written.append((part, rel, len(entries), sum(len(k) for _, _, k in entries)))
    for part, rel, n, m in written:
        print("%s: %d packages, %d permissions -> %s" % (part, n, m, rel))


if __name__ == "__main__":
    main()
